name: Deploy to AKS

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: saleortest2.azurecr.io
          username: ${{ secrets.ACR_username }}
          password: ${{ secrets.ACR_password }}
      
      - run: |
      
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
       
          creds: '${{secrets.AZURE_CREDENTIALS}}'
 
          resource-group: Testresgroup

          cluster-name: Testkbs
            
